# continuous integration
name: botentrain-ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the prod branch
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]

    environment: github_actions_bet #NODE_ENV=test
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      # npx force-resolutions : in case of Permission denied: run it locally to fix package-lock.json
      run: |
        echo "install"
        npm install
        echo "show outdated (if any)"
        npm outdated --depth=3 || echo "you must think about update your dependencies :)"

    - name: Run tests
      run: |
        echo "${{ secrets.TEST_ENV_FILE }}" >> ./env/.env.test
        npm run ci-test

    - name: Report coverage
      continue-on-error: true
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

    - name: Npm audit
      uses: oke-py/npm-audit-action@v1.7.1
      with:
        audit_level: moderate
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dedupe_issues: true